name: "El F칤sico Remoto - Autopilot"

on:
  push:
    branches:
      - main

jobs:
  run_physics_analysis:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout del Repositorio
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar Dependencias
      run: pip install -r requirements.txt
      
    - name: Ejecutar el An치lisis de F칤sica
      run: python scripts/analysis.py

    - name: Subir Gr치ficos y Resultados al Repositorio
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "游뱄 [Autopilot] Actualizaci칩n autom치tica de resultados (Gr치ficos)"
        files: results/*.png results/*.json
